g++ -o demo demo.cpp
g++ -o demo2 demo2.cpp
g++ -o demo3 demo3.cpp
g++ -o demo4 demo4.cpp
g++ -o demo5 demo5.cpp
g++ -o demo6 demo6.cpp
g++ -o demo7 demo7.cpp
g++ -o demo8 demo8.cpp
g++ -o demo9 demo9.cpp
